image: Ubuntu1804  # образ для сборки

      branches:
        only:
          - master  # ветка git

      build: off  # будем использовать свой скрипт сборки

      install:
        # запускаем SUT (запоминаем информацию о процессе в переменной $App)
        - java -jar ./artifacts/app-order.jar" -PassThru

      build_script:
        - ./gradlew test --info "-Dselenide.headless=true"  # стартуем Selenide в Headless-режиме (см.ниже)

      on_finish:
        - ps: Stop-Process -Id $App.Id  # оставливаем SUT